version: '3'

services:
    blocking_io:
        image: microservices-for-everyone/communication_styles_base
        build: docker/base/
        volumes:
            - ./:/opt
        ports:
            - 8080:80
        command: php -S 0.0.0.0:80 -t src/BlockingIO/web

    mixed_blocking_io:
        image: microservices-for-everyone/communication_styles_base
        volumes:
            - ./:/opt
        ports:
            - 8081:80
        command: php -S 0.0.0.0:80 -t src/MixedBlockingIO/web

    non_blocking_io:
        image: microservices-for-everyone/communication_styles_base
        volumes:
            - ./:/opt
        ports:
            - 8082:80
        command: php src/NonBlockingIO/web/index.php

    circuit_breaker:
        image: microservices-for-everyone/communication_styles_base
        volumes:
            - ./:/opt
        ports:
            - 8083:80
        command: php -S 0.0.0.0:80 -t src/CircuitBreakerBlockingIO/web

    flaky_service:
        image: microservices-for-everyone/communication_styles_base
        volumes:
            - ./:/opt
        ports:
            - 8084:80
        command: php -S 0.0.0.0:80 -t src/FlakyService/web

    lb:
        image: dockercloud/haproxy
        links:
            - slow_service1
            - slow_service2
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    slow_service1:
        image: microservices-for-everyone/communication_styles_base
        volumes:
            - ./:/opt
        ports:
            - 8085:80
        command: php -S 0.0.0.0:80 -t src/SlowService/web

    slow_service2:
        image: microservices-for-everyone/communication_styles_base
        volumes:
            - ./:/opt
        ports:
            - 8086:80
        command: php -S 0.0.0.0:80 -t src/SlowService/web

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            # management UI:
            - 15672:15672

    asynchronous_producer:
        image: microservices-for-everyone/communication_styles_base
        volumes:
            - ./:/opt
        command: php src/Asynchronous/producer.php
        depends_on:
            - rabbitmq

    asynchronous_consumer:
        image: microservices-for-everyone/communication_styles_base
        volumes:
            - ./:/opt
        command: php src/Asynchronous/consumer.php
        depends_on:
            - rabbitmq
